server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  cloud:
    consul:
      host: 192.168.198.128
      port: 8500
      discovery:
        instance-id: ${spring.application.name} # 注册的服务ID
        service_name: ${spring.application.name}
        ip-address: 192.168.0.107 # 指定 IP 地址
        prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always