server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

  cloud:
    consul:
      host: 192.168.198.128
      port: 8500
      discovery:
        service_name: ${spring.application.name}