server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false    #false表示 不想注册中心注册自己
    fetch-registry: false  #false表示自己就是注册中心，我的职责就是温和服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #enable-self-preservation: true  #开启自我保护
    enable-self-preservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 2000 #检测心跳信号的时间 默认90秒 改为2秒